name: ShoreCrash
main: com.shorecrash.CrashPlugin
version: 0.1.0
api-version: 1.21
authors: ["ShoreCrash"]
description: Crash mini-game with hologram chart and betting.
commands:
  crash:
    description: Place a crash bet before the round starts.
    usage: /crash <amount>
    aliases: [crashbet, bet]
  crashcashout:
    description: Cash out your active crash bet.
    usage: /crashcashout
    aliases: [cashout]
  crashholo:
    description: Manage the crash hologram location.
    usage: /crashholo set|clear
    aliases: [crashhologram]
  crashreload:
    description: Reload ShoreCrash configuration.
    usage: /crashreload
  crashadmin:
    description: Admin utilities for ShoreCrash.
    usage: /crashadmin rig <multiplier>
permissions:
  shorecrash.bet:
    description: Allow players to place crash bets.
    default: true
  shorecrash.cashout:
    description: Allow players to cash out during a round.
    default: true
  shorecrash.admin:
    description: Allow staff to manage hologram and reload configuration.
    default: op
